name: nc_image_reader
channels:
  - conda-forge
  - defaults
dependencies:
- python==3.8.3
- numpy
- xarray
- dask
- pip
- pip:
    - pygeobase
    - pynetcf
    - repurpose
    - pytest-cov<=2.9
    - coverage==4.5.2
    - pytest==3.8.2
